services:
 fastapi:
  image: swapnil092/fastapi:dev 
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 8000:8000

 streamlit:
  image: swapnil092/streamlit:dev
  build:
   context: ./streamlit_app
   dockerfile: Dockerfile
  ports:
   - 8501:8501
  environment:
   API_URL: http://fastapi:8000
